ARG VARIANT="jammy"
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04${VARIANT}

LABEL dev.containers.features="common"

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>